### PR TITLE
Update type hints

### PR DESCRIPTION
**Pull request by Diogo-Rossi**
# Description

- Add new function `upgradeMdb` found in `rpy` file
- Reorder imports in alphabetical order
- Add `Displayable` to inheritance of `Assembly`
- Add new symbolic constant
- Add missing `typing.Optional` in hints with `None`
- Replace all remaining `import typing` by `from typing import ...`
- Add `from __future__` import and new type corrections

### CODE REVIEW

**Comment by haiiliin** [comment]
There is a syntax error:
https://github.com/haiiliin/abqpy/blob/b23205a1686d4e8ebc7f63b25557afa20c99fa1f/src/abaqus/CustomKernel/RepositorySupport.py#L1

**Comment by Diogo-Rossi** [comment]
Is `auto_all` this package? https://pypi.org/project/auto-all/

**Comment by haiiliin** [comment]
> Is `auto_all` this package? https://pypi.org/project/auto-all/

Yes

**Comment by Diogo-Rossi** [comment]
There are some missing imports, I'm trying to solve that.

**Comment by haiiliin** [comment]
> There are some missing imports, I'm trying to solve that.

I am working on it.

**Comment by Diogo-Rossi** [comment]
> I am working on it.

Oh, I think I solved it. But there ir another issue in the `auto_all` module

**Comment by haiiliin** [comment]
> > I am working on it.
> 
> Oh, I think I solved it. But there ir another issue in the `auto_all` module

Great

**Comment by haiiliin** [comment]
Backport conflicts must be heavy for this pull request.

**Pull request merged**
