### PR TITLE
Correct some type checkings

### PR DESCRIPTION
**Pull request by Diogo-Rossi**
Basically changing the `SymbolicConstant` to be an `Enum` and allowing to be used in `typing.Literal`
Also annotate the alias `Boolean` to accept `True` and `False` (built in `bool`)

### CODE REVIEW

**Review by haiiliin — APPROVED** [review]

**Comment by haiiliin** [comment]
Documentation building fails, if you run `from abaqus.AbaqusCAEDisplayPreferences.caePrefsAccess import *`, a `TypeError: __hash__ method should return an integer` will be raised.

**Comment by Diogo-Rossi** [comment]
> __hash__ method should return an integer

Oh, that's strange. The [PEP 586](https://peps.python.org/pep-0586/#legal-parameters-for-literal-at-type-check-time) says that we can use `Enum` values in `Literal` types.

**Comment by haiiliin** [comment]
how about using IntEnum?

**Comment by Diogo-Rossi** [comment]
> how about using IntEnum?

I think I found the problem. `SymbolicConstant` class has a `__hash__` method. I'm removing that

**Comment by Diogo-Rossi** [comment]
But I'm seeing an error in `from .template import *`

```python
FileNotFoundError: File C:\path\to\file\compression.conf.toml does not exist.
```

**Comment by haiiliin** [comment]
I rebased the branch, can you test again?

**Comment by Diogo-Rossi** [comment]
Never mind, I was testing in another branch

**Comment by Diogo-Rossi** [comment]
The documentation building is yet failing, but I could not find what the error is.

**Comment by haiiliin** [comment]
An `Enum` object should have an attribute `name`, how about setting the `name` explicitly by `self.name = text`

**Comment by haiiliin** [comment]
An `Enum` object should have an attribute `name`, how about setting the `name` explicitly by `self.name = text`

**Comment by haiiliin** [comment]
By the way, I don't know whether it is a good idea to let the SymbolicConstant class inherits from both str and Enum, seems that they are not compatible with each other

**Comment by Diogo-Rossi** [comment]
> By the way, I don't know whether it is a good idea to let the SymbolicConstant class inherits from both str and Enum, seems that they are not compatible with each other

Yes, I tested without the `str` inheritance, and also without any other method, but still getting a error.

> An `Enum` object should have an attribute `name`, how about setting the `name` explicitly by `self.name = text`?

I don't understand why, `Enum` would have only constants, see [PEP 586](https://peps.python.org/pep-0586/#interactions-with-enums-and-exhaustiveness-checks)

**Comment by haiiliin** [comment]
Is it because Enum constants must be integers

**Comment by Diogo-Rossi** [comment]
> Is it because Enum constants must be integers

Oh, maybe. But, at run time it works... I'm checking

**Comment by Diogo-Rossi** [comment]
> An `Enum` object should have an attribute `name`, how about setting the `name` explicitly by `self.name = text`?

I ended up doing this. I made some search: it seems there is some issues in Sphinx when processing `Enum` classes ([[1]](https://stackoverflow.com/questions/59611074/sphinx-not-documenting-complex-enum-classes)[[2]](https://stackoverflow.com/questions/59611074/sphinx-not-documenting-complex-enum-classes)). There is still [this extension](https://enum-tools.readthedocs.io/en/latest/api/autoenum.html) that make it better to work with `Enum` (I tried that too, but didn't solve the problem).

> By the way, I don't know whether it is a good idea to let the SymbolicConstant class inherits from both str and Enum, seems that they are not compatible with each other

Actually, I found out we can work normally in this way. It is in [the docs](https://docs.python.org/3/library/enum.html#others:~:text=This%20demonstrates%20how%20similar%20derived%20enumerations%20can%20be%20defined%3B%20for%20example%20a%20StrEnum%20that%20mixes%20in%20str%20instead%20of%20int.) and [this guy made something similar](https://www.cosmicpython.com/blog/2020-10-27-i-hate-enums.html). 

I removed the reference to `SymbolicConstant ` class in the `.rst` file and then Sphinx runs ok, so the problem was really in Sphinx with `Enum`. Then, to keep the class doc, I put explicit variables `value` and `name` in the module, and the built becomes ok (locally).

I hope that it passes now.

**Comment by Diogo-Rossi** [comment]
> But I'm seeing an error in `from .template import *`
> 
> ```python
> FileNotFoundError: File C:\path\to\file\compression.conf.toml does not exist.
> ```

By the way, I was still getting this problem.
That's because it was trying to read from `./src/abqpy/templates/` folder. So I copied the `templates` folder to `./src/abqpy/` to make it work.
I don't know if that is an issue, because I'm working in the source code without doing `pip install .`
Maybe when installing the package, that error doesn't happen.

**Comment by haiiliin** [comment]
> > But I'm seeing an error in `from .template import *`
> > 
> > ```python
> > FileNotFoundError: File C:\path\to\file\compression.conf.toml does not exist.
> > ```
> 
> By the way, I was still getting this error.
> That's because it was trying to read from `./src/abqpy/templates/` folder. So I copied the `templates` folder to `./src/abqpy/` to make it work.
> I don't know if that is an issue, because I'm working in the source code without doing `pip install .`
> Maybe when installing the package, that error doesn't happen.

You are right, I want to keep the templates folder in the top-level folder but I can't package them normally, the `package_data`  in setuptools seems only able to package data files that is inside the package source, `src/abqpy`, so I copy the templates folder to `src/abqpy` explicitly:
https://github.com/haiiliin/abqpy/blob/4e0cc477046923adfe2e5c5565248b6e5a4fee1c/setup.py#L9-L12

It won't work if we don't install the package,  maybe we should just move the templates to `src/abqpy`, it seems not to be a good solution.

**Comment by haiiliin** [comment]
> > An `Enum` object should have an attribute `name`, how about setting the `name` explicitly by `self.name = text`?
> 
> I ended up doing this.
> I made some search: it seems there is some issues in Sphinx when processing `Enum` classes ([[1]](https://stackoverflow.com/questions/59611074/sphinx-not-documenting-complex-enum-classes), [[2]](https://stackoverflow.com/questions/62066645/difficulties-documenting-enum-classes), [[3]](https://stackoverflow.com/questions/17690437/sphinx-correct-way-to-document-an-enum), [[4]](https://stackoverflow.com/questions/69882764/doxygen-sphinx-and-forward-declared-enum-class)).
> There is still [this extension](https://enum-tools.readthedocs.io/en/latest/api/autoenum.html) that makes it better to work with `Enum` (I tried that too, but didn't solve the problem).
> 
> > By the way, I don't know whether it is a good idea to let the SymbolicConstant class inherits from both str and Enum, seems that they are not compatible with each other
> 
> > Is it because Enum constants must be integers
> 
> Actually, I found out we can work normally in this way. This is [in the docs](https://docs.python.org/3/library/enum.html#others:~:text=This%20demonstrates%20how%20similar%20derived%20enumerations%20can%20be%20defined%3B%20for%20example%20a%20StrEnum%20that%20mixes%20in%20str%20instead%20of%20int.) and [this guy made something similar](https://www.cosmicpython.com/blog/2020-10-27-i-hate-enums.html). 
> 
> I removed the reference to `SymbolicConstant ` class in the `.rst` file and then Sphinx runs ok, so the problem was really in Sphinx with `Enum`. Then, to keep the class doc, I put explicit variables `value` and `name` in the module, and the built becomes ok (locally).
> 
> I hope that it passes now.
> It is really strange that if works ehen you just add the `name` and `value` variables in the SymbolicConstants` module, but anyway, it works, so let's keep it this way.

**Comment by haiiliin** [comment]
This pull request seems quite good now, can I merge now? @Diogo-Rossi

**Comment by Diogo-Rossi** [comment]
> This pull request seems quite good now, can I merge now? @Diogo-Rossi 

I think you can

**Pull request merged**
