### PR TITLE
split command lines also in README

### PR DESCRIPTION
**Pull request by Diogo-Rossi**
Requested in #1434 

https://github.com/haiiliin/abqpy/pull/1434#issuecomment-1248882706

### CODE REVIEW

**Comment by haiiliin** [comment]
There should be conflicts in the backport pull requests, concerning with the version number, @Diogo-Rossi will you try to resolve it and remove the `conflicts` label?

**Comment by haiiliin** [comment]
@Mergifyio backport V2016 V2017 V2018 V2019 V2020 V2021 V2022

**Comment by Diogo-Rossi** [comment]
> There should be conflicts in the backport pull requests, concerning with the version number, @Diogo-Rossi will you try to resolve it and remove the `conflicts` label?

Ok. I'm not sure how to do it, but I'll try. Sorry, only now I saw your message.

**Comment by haiiliin** [comment]
> > There should be conflicts in the backport pull requests, concerning with the version number, @Diogo-Rossi will you try to resolve it and remove the `conflicts` label?
> 
> Ok. I'm not sure how to do it, but I'll try. Sorry, only now I saw your message.

never mind, I already did

**Comment by haiiliin** [comment]
Just for reference, several things to pay attention to when backport pull requests are in conflicts:
- When a backport pull request is in conflicts, a `conflicts` label will be assigned to this pull request, `mergify` will send a message like this, only files in `Unmerged paths:` need to be resolved.
  > This is an automatic backport of pull request #1476 done by [Mergify](https://mergify.com). Cherry-pick of [a9ef490](https://github.com/haiiliin/abqpy/commit/a9ef4904e1c4662584b3ffa926a6e352d2c424fb) has failed:
  > 
  > ```
  > On branch mergify/bp/V2022/pr-1476
  > Your branch is up to date with 'origin/V2022'.
  > 
  > You are currently cherry-picking commit a9ef490.
  >   (fix conflicts and run "git cherry-pick --continue")
  >   (use "git cherry-pick --skip" to skip this patch)
  >   (use "git cherry-pick --abort" to cancel the cherry-pick operation)
  > 
  > Changes to be committed:
  > 	modified:   README.md
  > 
  > Unmerged paths:
  >   (use "git add <file>..." to mark resolution)
  > 	both modified:   README-zh-cn.md
  > ```
  > 
  > To fix up this pull request, you can check it out locally. See documentation: https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
  > 
  > Mergify commands and options
- Files `deleted by us` occurs when we modified something that was introduced in a specific version, in the older branch, the file does not exist, in this condition, we can just delete these files.
  > ```
  > Unmerged paths:
  > (use "git add/rm <file>..." as appropriate to mark resolution)
  > 	deleted by us:   src/abaqus/Material/Plastic/CrushStress/CrushStress.py
  > ```
- When files are `both modified`, means we modified something that is different in different branches, in this condition we need to resolve the conflicts, usually, we can `Accept Current Change`, like this in VSCode:
  image
  and then introduced the new features we want to introduce for the old version. For simple modifications like it here when we modified code that is concerned with version number, we can `Accept Incoming Change` and modified the version number to an older version. 
- When conflicts are all resolved, we should remove the `conflicts` label, maybe the `mergify` will auto remove the conflicts when there are no conflicts, governing by this `mergify` rule, but I haven't tested this feature:
  https://github.com/haiiliin/abqpy/blob/d6a124ff98f85e976fae8b5c3c54ae6abcd96a08/.github/mergify.yml#L160-L166
- `mergify` will merge the pull request automatically (without turn on the `automerge` option manually), governing by this `mergify` rule:
  https://github.com/haiiliin/abqpy/blob/d6a124ff98f85e976fae8b5c3c54ae6abcd96a08/.github/mergify.yml#L140-L148

**Comment by haiiliin** [comment]
Posted a discussion about resolving backport conflicts in #1500.

**Pull request merged**
