### PR TITLE
Improve type hints

### PR DESCRIPTION
**Pull request by Diogo-Rossi**
# Description

In this pull request there is a lot of type annotations changes and doc string formatting, trying to improve type hints.

### CODE REVIEW

**Comment by haiiliin** [comment]
Seems that Python 3.7 does not support typing.Literal, please use typing_extensions.Literal

**Comment by Diogo-Rossi** [comment]
> Seems that Python 3.7 does not support typing.Literal, please use typing_extensions.Literal

Ok

**Comment by haiiliin** [comment]
Documentation build fails concerned with the `sphinx_autodoc_typehints` extension.

**Comment by Diogo-Rossi** [comment]
Yes. I can't figure why.

**Comment by haiiliin** [comment]
Here is an issue: tox-dev/sphinx-autodoc-typehints#259

**Comment by haiiliin** [comment]
I think it is due to a bug in `sphinx-autodoc-typehints v1.19.3`

**Comment by Diogo-Rossi** [comment]
Good catch! I wasn't find the error.

**Comment by haiiliin** [comment]
Maybe we should specify the version of `sphinx-autodoc-typehints` in `docs/requirements.txt` until the bug is fixed.

**Comment by Diogo-Rossi** [comment]
> Maybe we should specify the version of `sphinx-autodoc-typehints` to `1.19.2` in `docs/requirements.txt` until the bug is fixed.

ok

**Review by haiiliin — APPROVED** [review]

**Comment by haiiliin** [comment]
It is strange that readthedocs still installs `sphinx-autodoc-typehints==1.19.3` by `pip install -r docs/requirements.txt`: https://readthedocs.org/projects/abqpy/builds/18181304/

**Pull request merged**
